<?php

/**
 * Implements hook_menu().
 */
function imaginary_fix_maps_menu()
{
  $items = array();
  $items['admin/config/content/geofield-mapkey'] = array(
    'title' => 'Geofield map key settings',
    'description' => 'Configuration for the Geofield mapkey settings module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('imaginary_fix_maps_settings_form'),
    'access arguments' => array('administer site configuration'),
    );

  return $items;
}

function imaginary_fix_maps_settings_form($form, &$form_state) {

  $form['imaginary_fix_maps_map_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Google API Key'),
    '#default_value' => variable_get('imaginary_fix_maps_map_key', ''),
    '#size' => 60,
    '#maxlength' => 255,
    '#description' => t('Your Google API Key. This module will not work without it.'),
    '#required' => TRUE,
  );
  return system_settings_form($form);
}

/**
 * Implements hook_js_alter().
 */
function imaginary_fix_maps_js_alter(&$javascript)
{
  //for geofield input widget
  if(isset($javascript['//maps.google.com/maps/api/js?sensor=false'])) {
    $javascript['//maps.google.com/maps/api/js?sensor=false']['data'] .=
      '&key=' . variable_get('imaginary_fix_maps_map_key', '');
  }


  //for geofield map views style plugin ?! (I think)
  if(isset($javascript['//maps.googleapis.com/maps/api/js?sensor=false'])) {
    $javascript['//maps.googleapis.com/maps/api/js?sensor=false']['data'] .=
      '&key=' . variable_get('imaginary_fix_maps_map_key', '');
  }
}