<?php
/**
 * @file
 * Views comma-separated list.
 */

/**
 * Implements hook_theme().
 */
function views_delimited_list_theme() {
  return array(
    'views_delimited_list_fields' => array(
      'variables' => array(),
      'template' => 'views-delimited-list-fields',
    ),
  );
}

/**
 * Implements hook_theme_registry_alter().
 */
function views_delimited_list_theme_registry_alter(&$hooks) {
  // Copy variables from the original theme hook.
  $hooks['views_delimited_list_fields']['variables'] = $hooks['views_view_fields']['variables'];
}

/**
 * Implements hook_views_api().
 */
function views_delimited_list_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_views_view_delimited_list(&$vars) {
  $view = $vars['view'];

  // Process row classes
  $vars['classes_array'] = array();
  foreach ($vars['rows'] as $id => $_) {
    $vars['classes_array'][$id] = 'views-row';
  }
}

/**
 * Implements hook_preprocess_HOOK() for views_view_fields.
 */
function views_delimited_list_preprocess_views_view_fields(&$vars) {
  if (class_exists('views_plugin_style_delimited_list') && $vars['view']->style_plugin instanceof views_plugin_style_delimited_list) {
    // Inject the view template name to dispose Drupal towards using our template
    array_unshift($vars['theme_hook_suggestions'], 'views_delimited_list_fields');
  }
}
